---
title: "___"
author: "___, ___, ___, ___"
date: "`r Sys.Date()`"
format:
  html:
    code-fold: true
    code-tools: true
    toc: true
editor: visual
lang: fr
bibliography: bibliography/references.bib
---

<!--% Complétez l'entête en définissant un titre qui soit représentatif de votre travail. Indiquez aussi les noms des auteurs. -->

<!--# Dans les différentes sections, vous trouverez des indicateurs "...Vos XXX ici..." Vous devez bien sûr REMPLACER ces indicateurs par votre propre texte. Ne les laissez pas dans votre version finale du document. Vous devez travailler dans le même document (pas question de faire un document séparé par étudiant). Gérez les conflits éventuels. -->

```{r setup, include=FALSE}
# Ceci est nécessaire pour les tests SDD, ne pas utiliser dans un "vrai" projet
if (!"tools:tests" %in% search())
  source(here::here("tests/tools_tests.R"), attach(NULL, name = "tools:tests"))

# Configuration de l'environnement SciViews::R
SciViews::R("model", "infer", lang = "fr")
```

# Introduction

<!--% Sur base de la bibliographie (lecture de l'article fourni et de vos propres recherches sur Internet), rédigez une introduction du sujet en 3 à 4 paragraphes. Cette introduction doit guider le lecteur vers votre but. Vous devez citer vos sources, c'est-à-dire qu’il faut indiquer au minimum la référence bibliographique fournie de manière correcte (inspirez-vous de ce qui est indiqué dans le bloc-notes, mais reformulez : un simple copier-coller de l'introduction du bloc-notes n'est PAS considéré comme l'exercice réalisé !) -->

<!--# Ce projet porte sur la santé humaine liée à l'obésité, à la façon de se nourrir et aux activités réalisées (plus ou moins sédentaire ou actif) ... Réalisez des recherches bibliographiques afin d'avoir une vision précise de la thématique. Existe-t-il des indicateurs calculables pour quantifier l'état de santé d'un individu, par exemple ? Naturellement, ces indicateurs doivent être calculables sur bases des variables mesurées dans votre jeu de données. Focalisez-vous donc sur ces variables-là. -->

...Votre introduction ici...

# But

<!--% Formulez ici de façon concise et précise votre question de recherche en 1 à 2 phrases. -->

...Votre but ici...

# Matériel et méthodes

<!--% Cette section doit comprendre une explication technique sur les mesures effectuées et sur le protocole relatif à l'acquisition des données en 3 à 4 paragraphes. Vous ajouterez aussi un paragraphe qui détaille les outils logiciels et statistiques utilisés (logiciels et versions des logiciels). Un simple copier-coller du matériel et méthodes du bloc-notes ne sera PAS considéré comme acceptable. -->

...Votre matmet ici...

# Résultats

## Description des données

<!--% Extrayez les quelques éléments les plus pertinents (3 à 5) de votre document `human_notebook.qmd` pour décrire les données de manière cohérente par rapport au but. Reprenez les interprétations en les reformulant de manière concise pour former un texte qui se lit en continu (donc un texte plus construit que ce que vous avez indiqué dans le bloc-notes). -->

<!--# N'oubliez pas que ce document doit pouvoir compiler indépendamment du reste. Cela implique que vous ajoutiez un chunk d'importation des données et que vous recalculiez tout ce qui doit l'être... Par contre, un simple copier-coller de toute la partie résultats du bloc-notes ne sera pas considéré comme un travail réalisé : vous devez sélectionner, et éventuellement remanier un peu le code, pour ne conserver que ce qui est utile ici. -->

```{r, Description 1}
give_n <- function(x)
  c(y = max(x) * 1.03, label = length(x))
chart(biometry, taille~genre %fill=%genre)+
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75))+
  #geom_jitter(alpha=0.5, width=0.1)
  stat_summary(fun.data=give_n, geom= "text", hjust = 0.5)+
  labs(title="Graphique en violon avec les quantiles")
```

```{r, Description 2}
## Recodage de biometry$eau en biometry$eau_rec
biometry$eau_rec <- cut(biometry$eau,
  include.lowest = TRUE,
  right = FALSE,
  dig.lab = 4,
  breaks = c(0, 1, 2, 4)
)
give_n5 <- function(x)
  c(y = max(x) * 1.1, label = length(x))
chart(data = biometry,masse_corr ~ eau_rec %fill=% genre) + 
  geom_boxplot() + 
  stat_summary(fun.data=give_n5, geom= "text", hjust = 0.5, position = position_dodge(0.75)) + 
  xlab("Consommation d'eau quotidienne (L/j)")

```
## Tests d'hypothèses

<!--% Sélectionnez les 4 tests d'hypothèses les plus pertinents depuis `human_notebook.qmd`, ainsi bien sûr que les calculs des indices nécessaires que vous placerez juste au-dessus de vos tests. Ces tests doivent répondre à votre question de recherche (le but). Reformulez les interprétations pour former un texte qui se lit en continu. -->

```{r plot_t_2}
## Recodage de biometry$fumeur en biometry$fumeur_rec_yes_no
biometry$fast_food_rec_yes_no <- cut(biometry$fast_food,
  include.lowest = TRUE,
  right = FALSE,
  dig.lab = 4,
  breaks = c(-100, 2.1, 1000),
  labels=c("0-2", ">=3")
)
label(biometry$fast_food_rec_yes_no)<- "Consommation de fast-food"
units(biometry$fast_food_rec_yes_no) <- "nombre/mois"
#biometry%>.%
#  sselect(., fast_food, fast_food_rec_yes_no)->
#  verif_fastfood
#skimr::skim(verif_fastfood)

chart(data= biometry, bmi~fast_food_rec_yes_no)+
  geom_jitter(width=0.3, alpha=0.2)+
  stat_summary(geom="point", fun="mean")+
  stat_summary(geom="errorbar", width=0.3, fun.data="mean_cl_normal", fun.args = list(conf.int = 0.95))

```

```{r plot_anova1_2}
## Recodage de biometry$sucre en biometry$sucre_rec
biometry$sucre_rec <- biometry$sucre %>%
  fct_recode(
    "jamais à rarement" = "jamais",
    "jamais à rarement" = "rarement"
  )

chart(data=biometry, tour_taille~sucre_rec)+
  geom_violin()+
  geom_jitter(width=0.1, alpha=0.5)+
  stat_summary(geom="point", fun="mean", col="red", size=3)
  
```


<!--% Hypothèse nulle et alternative -->

H0 : mean(bmi\|ff\<=2)=mean(bmi\|ff\>3) H1 : mean(bmi\|ff\<=2)!=mean(bmi\|ff\>3) <!--% Vérification des conditions d'application -->

```{r test_t_2}
# Conversion en vecteur numérique 
biometry$bmi <- as.numeric(biometry$bmi)

car::qqPlot(biometry$bmi, distribution = "norm", envelope = 0.95, col = "blue")

#Test 
t.test(data= biometry, bmi~fast_food_rec_yes_no, alternative= "two.sided", conf.level= 0.95, var.equal=TRUE)



```
<!--% Hypothèse nulle et alternative -->

H0 : Les moyennes sont égales.

H1 : Au moins une des moyennes diffère des autres.

<!--% Vérification des conditions d'application -->

```{r test_anova1_2}
sucre_lm<-lm(data= biometry, tour_taille ~sucre_rec)
tabularise(anova(sucre_lm))
#Vérif homoscédasticité
bartlett.test(data=biometry,tour_taille ~sucre_rec)
#Résidus qqplot
chart$qqplot(sucre_lm, lang="fr")
#post hoc
summary(sucre_confint<-confint(multcomp::glht(sucre_lm, linfct=multcomp::mcp(sucre_rec="Tukey"))))

oma<-par(oma=c(0,9.5,0,0))
plot(sucre_confint)
par(oma)
rm(oma)
```


```{r plot_anova2_1}
table(biometry$fast_food_rec_yes_no, biometry$sucre_rec)

biometry %>.%
  sgroup_by(., fast_food_rec_yes_no, sucre_rec) %>.%
  ssummarise(., BMI_moyen = mean(bmi, na.rm = TRUE)) %>.%
chart(data = ., BMI_moyen ~ sucre_rec %col=%fast_food_rec_yes_no  %group=% fast_food_rec_yes_no) +
    geom_line() +
    geom_point()

```
# Discussion et conclusions

<!--% Reprenez les résultats obtenus, discutez-les d'un point de vue biologique en 4 à 5 paragraphes et concluez votre travail. Vous pouvez les mettre également en relation avec vos recherches bibliographiques dans cette section. -->

...Vos conclusions ici...

<!--# Important : ce document doit compiler SANS ERREURS avec le bouton 'Rendu' sinon le travail sera sanctionné lourdement. La compilation du document Quarto est maintenant considérée comme acquise. -->

# Référence

<!--% N'indiquez rien ci-dessous. Quarto se chargera de rajouter vos références bibliographiques automatiquement. -->
